Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.metrics import accuracy_score

# Membuat prediksi menggunakan data testing
test_pred = regresor.predict(test)

# Menghitung akurasi
accuracy = accuracy_score(test_label, test_pred)

print("Akurasi KNN: {:.2f}%".format(accuracy * 100))

------------------


[0;31m[0m
[0;31mAttributeError[0mTraceback (most recent call last)
[0;32m<ipython-input-9-0b5d10267287>[0m in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;31m# Membuat prediksi menggunakan data testing[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mtest_pred[0m [0;34m=[0m [0mregresor[0m[0;34m.[0m[0mpredict[0m[0;34m([0m[0mtest[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0;31m# Menghitung akurasi[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'NearestNeighbors' object has no attribute 'predict'

